# Generated by Django 2.1 on 2018-10-20 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_acadamicmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='acadamicModel',
            new_name='academicModel',
        ),
    ]
