# Generated by Django 2.1 on 2018-10-21 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_certificatemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='certificateModel',
        ),
    ]
