# Generated by Django 2.1 on 2018-10-21 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_delete_certificatemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='certificateModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'certificate',
            },
        ),
    ]
