# Generated by Django 2.1 on 2018-10-22 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_projecteditmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='projectEditModel',
        ),
    ]
