# Generated by Django 2.1 on 2018-10-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_delete_projecteditmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='projectEditModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('picOfPro', models.ImageField(default='static/None/no-img.png', upload_to='static/')),
                ('description', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'project_edit',
            },
        ),
    ]
