# Generated by Django 2.1 on 2018-10-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20181022_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecteditmodel',
            name='picOfPro',
            field=models.ImageField(default='app/static/media/no-img.png', upload_to='app/static/media/'),
        ),
    ]
