# Generated by Django 2.1 on 2018-10-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20181022_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecteditmodel',
            name='link',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
