# Generated by Django 2.1 on 2018-10-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_projecteditmodel_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecteditmodel',
            name='picOfPro',
            field=models.ImageField(default='no-img.png', upload_to='app/static/media/'),
        ),
    ]
