# Generated by Django 2.1 on 2018-10-24 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20181023_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecteditmodel',
            name='picOfPro',
            field=models.ImageField(default='/static/media/no-img.png', upload_to='app/static/media/'),
        ),
    ]
